// resources/js/utils/pdfGenerator.js
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

/**
 * Generate a styled, full-page PDF of any element.
 * @param {String} selector - CSS selector ng container (hal. "#reportSection")
 * @param {Object} options - Optional customization
 */
export async function generateStyledPDF(selector, options = {}) {
  const element = document.querySelector(selector);
  if (!element) {
    alert("Walang element na ma-e-export sa PDF.");
    return;
  }

  const {
    filename = `AI-Report-${new Date().toISOString().slice(0, 10)}.pdf`,
    scale = 2,
    margin = 20,
    headerText = "Agent Products Demo Trials Report",
    footerText = "Generated by AI-Agent System",
  } = options;

  const canvas = await html2canvas(element, {
    scale,
    useCORS: true,
    backgroundColor: "#ffffff",
  });

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "px",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const imgWidth = pageWidth - margin * 2;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let heightLeft = imgHeight;
  let position = margin;

  // Add header
  pdf.setFontSize(14);
  pdf.text(headerText, margin, 30);

  // Add first page image
  pdf.addImage(imgData, "PNG", margin, 50, imgWidth, imgHeight);
  heightLeft -= pageHeight - 50;

  // Handle multi-page content
  while (heightLeft > 0) {
    pdf.addPage();
    position = heightLeft - imgHeight + 50;
    pdf.addImage(imgData, "PNG", margin, position, imgWidth, imgHeight);
    heightLeft -= pageHeight - 50;
  }

  // Add footer on the last page
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.text(
      `${footerText} | Page ${i} of ${totalPages}`,
      margin,
      pageHeight - 10
    );
  }

  pdf.save(filename);
}
